### ISSUE TITLE
As a user(android), I would like to create a local emergency event via detecting my scream so that I can ask for help even if I can’t access my phone physically

### ISSUE THREAD

**Issue by debestepe** [PaxCity/HearMyVoice-main#10]

**Comment by makinci** [comment]
(This issue depends on #7 , #22 , #14 , #23  and #9 )

This is a part of our native Android application.

It should talk to the APIs implemented in #23 . This feature should run in background. When scream is detected by using microphone, program should get current location of phone for the current user. With collected location, phone event type(panic_scream) and user id data, post this request to server.

**Comment by makinci** [comment]
Instead of the scream detection module, the detection will be performed with speech to text.
