### ISSUE TITLE
As a phone(android), I would like to catch local emergency events and notify server with user information, time and location so that I can ask for help on behalf of my user

### ISSUE THREAD

**Issue by debestepe** [PaxCity/HearMyVoice-main#11]

**Comment by bilgesubuk** [comment]
(This issue depends on #8 and #5 )
After an event created by button(#8) or detected scream(#5), this issue should get necessary informations and sent to backend (#23).

**Comment by bilgesubuk** [comment]
JSON Emergency Event is created in #8 according to JSON Android Emergency Event Object Structure (#23 ). Sending the POST request to **/android_emergency** endpoint with created JSON when emergency button is clicked. (#8)
