### ISSUE TITLE
As a web frontend, I would like to provide a page for system user authentication so that system users send their information for authentication to server and receive authentication tokens from server. 

### ISSUE THREAD

**Issue by bilgesubuk** [PaxCity/HearMyVoice-main#12]

**Comment by dgumus** [comment]
(This depends on #22)
From the authentication informations which created by #22, with the response data and tables in database,  tokens will be collected and shown on web page so that admins will be able to see the users from Android application and their status.

**Comment by bilgesubuk** [comment]
(This depends on #12 )

This issue contains user sign in page. Get user information from page and POST to backend for authentication system.
With response message that contains authentication token, current user of system is set.

**Comment by bilgesubuk** [comment]
For this task register and login pages is added. 
Navbar has been added to make the website useful. Until a new user logs in the system, there are login and create new users on the navbar. When current user is set by login at backend, only the log out field appears. Also the admin panel will be only accessed from Navbar.
