### ISSUE TITLE
As a phone(android), I would like to ask my user if the emergency request is real before creating events so that false positive emergency requests can be reduced

### ISSUE THREAD

**Issue by debestepe** [PaxCity/HearMyVoice-main#13]

**Comment by makinci** [comment]
This depends on #10. 
When scream is detected, a popup screen will be displayed for confirming the sending of alarms to the authorities and contact list. The alarm will be sent if the user does not answer for a certain period of time. (Approximately 10 seconds)

**Comment by makinci** [comment]
Completed with android text-to-speech.
