### ISSUE TITLE
As a user(android), I would like to add my emergency contact list via phone app so that my family can be notified in an emergency

### ISSUE THREAD

**Issue by debestepe** [PaxCity/HearMyVoice-main#15]

**Comment by dgumus** [comment]
(This issue depends on #7 and #25 )

Creating an android form for visuality of contact list. With this contact list via phone, user should be able to notify in an emergency. Send post request to backend with user information in an emergency. Also, add, delete, edit and notify is needed. All request need to be done with the same backend request #25
