### ISSUE TITLE
As a user(android), I would like to turn off the scream detection feature when I don’t need it so that I can reduce the false positive emergency events

### ISSUE THREAD

**Issue by debestepe** [PaxCity/HearMyVoice-main#16]

**Comment by dgumus** [comment]
(This issue depends on #10, #22  and #23 )

That feature is for the close the scream detection when user do not want to work this application in background and listen the environment. This will be implemented over #10 when shape of the event done. After turn off the scream detection the event type will be deactivate, no post to server.
