### ISSUE TITLE
As a server, I would like to deactivate events with system user request(from web interface) so that outdated events can be deactivated manually.

### ISSUE THREAD

**Issue by bilgesubuk** [PaxCity/HearMyVoice-main#17]

**Comment by debestepe** [comment]
(Be in close communication with the developers of #6  )

This is a part of the backend which handles event statuses. When a request with the event ID sent to this API, API updates the event status to "inactive".

**Comment by debestepe** [comment]
API endpoint URL will be "/deactivate_event". JSON object which contains event information should be sent to this endpoint via a POST request. 
##### JSON Event Object Structure
```json
{
    "user_id" : "<userid>",
    "event_id": "<event_id>"
}
```

**Comment by debestepe** [comment]
The response of the post request contains a status text ("OK" or "FAIL") and a message. In an error, the status will be "FAIL" and the message will be the error type. Also, HTTP status code will match the error type. 

##### JSON Response Object Structure
```json
{
    "status" : "<status>",
    "msg" :  "<message>"
}
```
