### ISSUE TITLE
As a server, I would like to provide event lists with given restrictions to web interface so that system users can see the emergency events.

### ISSUE THREAD

**Issue by bilgesubuk** [PaxCity/HearMyVoice-main#20]

**Comment by utkuaysev** [comment]
(This depends on #23 )
From events in database which created by #23, this API will collect and return event list with HTTP GET. This event list contains event status, date. Depends on event type (phone or sensor event) user or sensor information will be sent.

**Comment by utkuaysev** [comment]
Event informations will be send to web interface with endpoint **/getEvents**  with AJAX,HTTP GET.These informations will be getted from **Event** table.

**JSON Event Object Structure**
phoneEvent:{
    "event_id" : "<event_id>",
    "event_status": "<event_status>",
    "event_date": "<event_date>",
    "location": "<event_location>",
    "type": "<event_type>",
    "user_id": "<user_id>",
    "user_name": "<user_name>",
    "user_surname": "<user_surname>",
    "user_telephone": "<user_telephone>",
    "user_address": "<user_address>",
    "user_mail": "<user_mail>",
}
sensor_event{
    "event_id" : "<event_id>",
    "event_status": "<event_status>",
    "event_date": "<event_date>",
    "sensor_id": "<sensor_id>",
    "location": "<location>"
}
