### ISSUE TITLE
As a server, I would like to authenticate system(admin) users via web interface with their personal information on the database user table or create a new user if it does not already exist so that only authorized people can access the web interface.

### ISSUE THREAD

**Issue by bilgesubuk** [PaxCity/HearMyVoice-main#21]

**Comment by debestepe** [comment]
(Be in close communication with the developers of #12 )

This API provides the authentication feature to the web interface. When a new admin user signed up, API creates a user in the database with the given information. When an admin user attempts to log in, API checks if the information on the database and the given information matches.
