### ISSUE TITLE
As a server, I would like to authenticate mobile app users with their personal information on the database user table or create a new user if it does not already exist so that I can know the person who sent the emergency event

### ISSUE THREAD

**Issue by debestepe** [PaxCity/HearMyVoice-main#22]

**Comment by utkuaysev** [comment]
From POST request getted from android, user information will be added to database. Also build a authentication system to check current android user.

**Comment by utkuaysev** [comment]
Be in a close relationship with developers of #7

**Comment by utkuaysev** [comment]
For current users; authenticated will updated to true.endpoint is **login**

**JSON Android Authenticate Current User Structure**
```
{
    "ssn" : "<ssn>",
}
```

**Comment by utkuaysev** [comment]
For new users; user will be added to **User** table.Endpoint is **newUser**
**JSON Android Add New User Structure**
```
{
    "ssn" : "<ssn>",
    "name": "<name>",
    "surname": "<surname>",
    "address": "<address>",
    "telephoneNumber": "<telephoneNumber>",
    "email": "<email>",
}
```
