### ISSUE TITLE
As a server background job, I would like to update emergency events in the database to inactive if the event is older than 2 days so that outdated events can be separated from current events.

### ISSUE THREAD

**Issue by bilgesubuk** [PaxCity/HearMyVoice-main#24]

**Comment by utkuaysev** [comment]
(This depends on #23 and #19 )
If an event becomes outdated, status of this event should be updated and event status will be setted to inactive. This check will be done in every two days.

**Comment by utkuaysev** [comment]
For reach that purpose; firstly create **/deactivateEventCron()** function.This functions process query for get active events.With this events;performs check for if this event is outdated.Set status of outdated events to **False**
