### ISSUE TITLE
As a server, I would like to send notifications to users emergency contacts when notification event triggered so that people in the emergency contact list can be notified.

### ISSUE THREAD

**Issue by bilgesubuk** [PaxCity/HearMyVoice-main#25]

**Comment by utkuaysev** [comment]
When notification event triggered, from collected emergency list in #26 for each emergency contact in database should be notified by server.

**Comment by utkuaysev** [comment]
For the purpose of mock;**notify_test()**  function will be created.Gets json request and notifies related contacts.

 **JSON Notify Contacts Structure**
```
{
    "user_id" : "<user_id>",
    "event_id":"<event_id>"
}

```
