### ISSUE TITLE
As a server, I would like to create/update/delete user emergency contact lists in the database so that emergency contacts which is used for sending notifications, always be up-to-date.

### ISSUE THREAD

**Issue by bilgesubuk** [PaxCity/HearMyVoice-main#26]

**Comment by debestepe** [comment]
(Be in close communication with the developers of #15)

This is a part of the backend which handles emergency contact lists between android application and database. When changes in the contact list are saved, a request(w/user information) is sent to this API. API processes the request and makes changes to the contact table with the user ID.

**Comment by debestepe** [comment]
API endpoint URL will be "/update_contacts". JSON object which contains the contacts and user information should be sent to this endpoint via a POST request.

##### JSON Contact Object Structure
```json
{
    "user_id" : "<userid>",
    "contacts": [
        {
            "name": "<contact_name>",
            "surname": "<contact_surname>",
            "phone_number": "<contact_phone_number>",
            "email": "<contact_email>"
        }
    ]
}
```

**Comment by debestepe** [comment]
The response of the post request contains a status text ("OK" or "FAIL") and a message. In an error, the status will be "FAIL" and the message will be the error type. Also, HTTP status code will match the error type. 

##### JSON Contact Response Object Structure
```json
{
    "status" : "<status>",
    "msg" :  "<message>"
}
```

**Comment by debestepe** [comment]
#41 feature also added for the future usage.
