### ISSUE TITLE
As a web frontend, I would like to provide sensor information page so that system users(admins) can create/update/delete sensors and their locations

### ISSUE THREAD

**Issue by debestepe** [PaxCity/HearMyVoice-main#27]

**Comment by makinci** [comment]
(This depends on #19 and #4 . Be in close communication with the developers of #19 and #4 )

This is a web frontend that should provide pages implented via HTML/Javascript/JSON. The application should use AJAX/JQuery or similar technologies to make the interaction responsive.

System admins can create and delete sensors which are located in city. Location and sensor id information will be post to backend.
