### ISSUE TITLE
(Planning) As a developer team, we would like to create an ER diagram and a relational model for the project database so that we can work independently with a common data model

### ISSUE THREAD

**Issue by debestepe** [PaxCity/HearMyVoice-main#3]

**Comment by utkuaysev** [comment]
![IMG-20200118-WA0007](https://user-images.githubusercontent.com/33395066/72663296-25fe7480-3a02-11ea-9030-50c660a250a2.jpeg)

**Comment by bilgesubuk** [comment]
![WhatsApp Image 2020-01-21 at 18 00 14](https://user-images.githubusercontent.com/32189747/72815816-4a638680-3c78-11ea-88d7-2924ddf5969b.jpeg)

**Comment by makinci** [comment]
![WhatsApp Image 2020-01-21 at 18 41 15](https://user-images.githubusercontent.com/30000785/72819213-e8a61b00-3c7d-11ea-982c-bef22dc8cb53.jpeg)

Relational Model is completed.

**Comment by utkuaysev** [comment]
![WhatsApp Image 2020-02-05 at 12 26 59](https://user-images.githubusercontent.com/33395066/73866558-0ee9c000-4813-11ea-9623-8ad1c43762c7.jpeg)

ER is updated.**Authenticated** column is added to **User** table.Primary keys are highlighted
