### ISSUE TITLE
As a web frontend, I would like to provide a list page and query restrictions area so that system admins can see the list of events which meet the given criteria.

### ISSUE THREAD

**Issue by bilgesubuk** [PaxCity/HearMyVoice-main#6]

**Comment by dgumus** [comment]
(This depends on #19 . Be in close communication with the developers of #19)

This is a web frontend that should provide pages implented via HTML/Javascript/JSON. The application should use AJAX/JQuery or similar technologies to make the interaction responsive.

System admins are able to access the event to see the locations and event activity. For that purpose, sensor and android event ids will be use.
