### ISSUE TITLE
As a user(android), I would like to create a local emergency event via panic button so that I can ask for help with my phone

### ISSUE THREAD

**Issue by debestepe** [PaxCity/HearMyVoice-main#8]

**Comment by bilgesubuk** [comment]
(This issue depends on #7, #22, #14, #23 and #9 )

This is a part of our native Android application 

It should talk to the APIs implemented in #23 . This screen should provide a emergency button. When button is pushed, program should get current location of phone for the current user. With collected location, phone event type(panic_button) and user id data, post this request to server.
